services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genai-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AzureOpenAI__Endpoint=https://genai-chat-v2-resource.services.ai.azure.com
      - AzureOpenAI__Deployment=gpt-5-mini 
  